version: "3.8"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    image: "{{ app_image }}"
    container_name: "nodejs-api-{{ commit_hash.stdout }}"
    networks:
      - intranet
    ports:
      - 3100:3100

  caddy:
    image: caddy
    container_name: nodejs-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./caddy
        target: /etc/caddy
    networks:
      - intranet

networks:
  intranet:
