version: "3.8"

services:
  caddy:
    image: caddy
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./caddy
        target: /etc/caddy
    networks:
      - intranet

networks:
  intranet:
