---
- name: authenticate docker
  command: docker login ghcr.io -u USERNAME --password-stdin
  args:
    stdin: "{{ gh_personal_access_token }}"

- name: set domain
  set_fact:
    app_domain: "{{ domain_map[app_env] }}"

- name: configure caddy
  block:
    - name: ensure caddy folder exists
      file:
        path: ~/caddy/sites
        state: directory

    - name: copy root caddyfile
      template:
        src: caddy/Caddyfile
        dest: ~/caddy/Caddyfile

    - name: copy site specific caddyfile
      template:
        src: caddy/sites/Caddyfile.j2
        dest: ~/caddy/sites/{{ app_domain }}

- name: configure docker config
  block:
    - name: copy root docker-compose
      template:
        src: docker-compose.yml
        dest: ~/docker-compose.yml

    - name: copy site specific docker-compose
      template:
        src: docker-compose.yml.j2
        dest: ~/docker-compose-{{ app_env }}.yml

- name: run services
  block:
    - name: common services
      command: "{{ item }}"
      with_items:
        - docker-compose -f docker-compose.yml up -d caddy
        - docker-compose restart caddy

    - name: app service
      command: docker-compose -f docker-compose.yml -f docker-compose-{{ app_env }}.yml up -d {{ app_container }}
