---
- name: authenticate docker
  command: docker login ghcr.io -u USERNAME --password-stdin
  args:
    stdin: "{{ gh_personal_access_token }}"

- name: Set domain
  set_fact:
    app_domain: "{{ domain_map[app_env] }}"

- name: copy docker config
  template:
    src: docker-compose.yml.j2
    dest: ~/docker-compose.yml

- name: ensure caddy folder exists
  file:
    path: ~/caddy/sites
    state: directory

- name: copy root caddy file
  template:
    src: Caddyfile
    dest: ~/caddy/Caddyfile

- name: copy caddy sites config
  template:
    src: Caddyfile.j2
    dest: ~/caddy/sites/{{ app_domain }}

- name: run services
  command:
    cmd: docker-compose up -d

- name: reload caddy
  command:
    cmd: docker restart caddy
