---
- name: Authenticate docker
  command: docker login ghcr.io -u USERNAME --password-stdin
  args:
    stdin: "{{ gh_personal_access_token }}"

- name: Ensure caddy folder exists
  file:
    path: ~/caddy
    state: directory

- name: Copy docker config
  template:
    src: docker-compose.yml
    dest: ~/docker-compose.yml

- name: Copy caddy config
  template:
    src: caddy/Caddyfile
    dest: ~/caddy/Caddyfile

- name: Run services
  command:
    cmd: docker-compose up -d
