#!/usr/bin/env bash

GH_DEPLOY_TOKEN=$(grep GH_PERSONAL_ACCESS_TOKEN .env | tail -n1 | cut -d '=' -f2)

ENVIRONMENT=$1 # production, staging, dev
BRANCH=$2

curl \
    -X POST  \
    -H 'Accept: application/vnd.github.everest-preview+json' \
    -H "Authorization: token $GH_DEPLOY_TOKEN" \
    https://api.github.com/repos/ashishkpoudel/nodejs-ansible/dispatches \
    --data '{"event_type": "deploy-service", "client_payload": {"environment": "'"$ENVIRONMENT"'", "ref": "'"$BRANCH"'"}}' \
