---
- name: deploy application
  hosts: ApiServer
  vars_files:
    - "vars/common.yml"
  vars_prompt:
    - name: app_env
      prompt: App env to deploy
    - name: gh_personal_access_token
      prompt: Github Personal Access Token
  roles:
    - deploy
