name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        default: 'dev-production'
        options:
          - dev-dev
          - dev-production
          - production
      platforms:
        description: 'App platforms'
        required: true
        type: choice
        default: all
        options:
          - all
          - ios
          - android
      backend:
        description: 'Backend'
        required: false
      message:
        description: 'Message'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Get the commit reference
        run: |
          echo "$echo github sha: ${{ github.sha }}"

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install ansible boto3

      - name: Git sha output
        run: |
          echo "github_sha: ${{ github.ref }}"

      - name: Setup ssh credentials
        working-directory: cicd
        run: |
          mkdir -p ./credentials
          echo "${{ secrets.SSH_KEY }}" > ./credentials/ssh-key.pem
          chmod 400 ./credentials/ssh-key.pem

      - name: Run ansible playbook
        working-directory: cicd
        run: ansible-playbook --verbose deploy.yml --extra-vars "app_env=${{ github.event.client_payload.environment }} gh_personal_access_token=${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-container:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get the commit reference
        run: |
          echo "$echo github sha: ${{ github.sha }}"
